services:
  flask-app-1:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: flask-app
    container_name: flask-app-1
    expose:
      - "5000"
    volumes:
      - ./app:/app
    networks:
      - ssl

  flask-app-2:
    image: flask-app
    container_name: flask-app-2
    expose:
      - "5000"
    volumes:
      - ./app:/app
    networks:
      - ssl

  flask-app-3:
    image: flask-app
    container_name: flask-app-3
    expose:
      - "5000"
    volumes:
      - ./app:/app
    networks:
      - ssl

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-proxy
    container_name: nginx-proxy
    depends_on:
      # - flask-app-1
      - flask-app-2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ssl

networks:
  ssl:
    name: ssl
    driver: bridge
